#include "vgg16.h"

void vgg16(char *type, char *path)
{
    Graph *g = create_graph();
    Layer *l1 = make_convolutional_layer(64, 3, 1, 1, 1, "relu");
    Layer *l2 = make_convolutional_layer(64, 3, 1, 1, 1, "relu");
    Layer *l3 = make_maxpool_layer(2, 2, 0);
    Layer *l4 = make_convolutional_layer(128, 3, 1, 1, 1, "relu");
    Layer *l5 = make_convolutional_layer(128, 3, 1, 1, 1, "relu");
    Layer *l6 = make_maxpool_layer(2, 2, 0);
    Layer *l7 = make_convolutional_layer(256, 3, 1, 1, 1, "relu");
    Layer *l8 = make_convolutional_layer(256, 3, 1, 1, 1, "relu");
    Layer *l9 = make_convolutional_layer(256, 3, 1, 1, 1, "relu");
    Layer *l10 = make_maxpool_layer(2, 2, 0);
    Layer *l11 = make_convolutional_layer(512, 3, 1, 1, 1, "relu");
    Layer *l12 = make_convolutional_layer(512, 3, 1, 1, 1, "relu");
    Layer *l13 = make_convolutional_layer(512, 3, 1, 1, 1, "relu");
    Layer *l14 = make_maxpool_layer(2, 2, 0);
    Layer *l15 = make_convolutional_layer(512, 3, 1, 1, 1, "relu");
    Layer *l16 = make_convolutional_layer(512, 3, 1, 1, 1, "relu");
    Layer *l17 = make_convolutional_layer(512, 3, 1, 1, 1, "relu");
    Layer *l18 = make_maxpool_layer(2, 2, 0);
    Layer *l19 = make_connect_layer(4096, 1, "relu");
    Layer *l20 = make_dropout_layer(0.5);
    Layer *l21 = make_connect_layer(4096, 1, "relu");
    Layer *l22 = make_dropout_layer(0.5);
    Layer *l23 = make_connect_layer(2, 1, "linear");
    Layer *l24 = make_crossentropy_layer(2);
    append_layer2grpah(g, l1);
    append_layer2grpah(g, l2);
    append_layer2grpah(g, l3);
    append_layer2grpah(g, l4);
    append_layer2grpah(g, l5);
    append_layer2grpah(g, l6);
    append_layer2grpah(g, l7);
    append_layer2grpah(g, l8);
    append_layer2grpah(g, l9);
    append_layer2grpah(g, l10);
    append_layer2grpah(g, l11);
    append_layer2grpah(g, l12);
    append_layer2grpah(g, l13);
    append_layer2grpah(g, l14);
    append_layer2grpah(g, l15);
    append_layer2grpah(g, l16);
    append_layer2grpah(g, l17);
    append_layer2grpah(g, l18);
    append_layer2grpah(g, l19);
    append_layer2grpah(g, l20);
    append_layer2grpah(g, l21);
    append_layer2grpah(g, l22);
    append_layer2grpah(g, l23);
    append_layer2grpah(g, l24);
    init_kaiming_uniform(l1, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l2, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l4, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l5, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l7, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l8, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l9, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l11, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l12, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l13, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l15, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l16, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l17, sqrt(5.0), "fan_in", "leaky_relu");

    init_kaiming_uniform(l19, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l21, sqrt(5.0), "fan_in", "leaky_relu");
    init_kaiming_uniform(l23, sqrt(5.0), "fan_in", "leaky_relu");
    Session *sess = create_session(g, 224, 224, 3, 2, type, path);
    float *mean = calloc(3, sizeof(float));
    float *std = calloc(3, sizeof(float));
    mean[0] = 0.485;
    mean[1] = 0.456;
    mean[2] = 0.406;
    std[0] = 0.229;
    std[1] = 0.224;
    std[2] = 0.225;
    transform_normalize_sess(sess, mean, std);
    transform_resize_sess(sess, 224, 224);
    set_train_params(sess, 10, 32, 32, 0.001);
    SGDOptimizer_sess(sess, 0.9, 0, 0, 0, 0);
    init_session(sess, "./data/dogvscat/train.txt", "./data/dogvscat/train_label.txt");
    train(sess);
}

void vgg16_detect(char*type, char *path)
{
    Graph *g = create_graph();
    Layer *l1 = make_convolutional_layer(64, 3, 1, 1, 1, "relu");
    Layer *l2 = make_convolutional_layer(64, 3, 1, 1, 1, "relu");
    Layer *l3 = make_maxpool_layer(2, 2, 0);
    Layer *l4 = make_convolutional_layer(128, 3, 1, 1, 1, "relu");
    Layer *l5 = make_convolutional_layer(128, 3, 1, 1, 1, "relu");
    Layer *l6 = make_maxpool_layer(2, 2, 0);
    Layer *l7 = make_convolutional_layer(256, 3, 1, 1, 1, "relu");
    Layer *l8 = make_convolutional_layer(256, 3, 1, 1, 1, "relu");
    Layer *l9 = make_convolutional_layer(256, 3, 1, 1, 1, "relu");
    Layer *l10 = make_maxpool_layer(2, 2, 0);
    Layer *l11 = make_convolutional_layer(512, 3, 1, 1, 1, "relu");
    Layer *l12 = make_convolutional_layer(512, 3, 1, 1, 1, "relu");
    Layer *l13 = make_convolutional_layer(512, 3, 1, 1, 1, "relu");
    Layer *l14 = make_maxpool_layer(2, 2, 0);
    Layer *l15 = make_convolutional_layer(512, 3, 1, 1, 1, "relu");
    Layer *l16 = make_convolutional_layer(512, 3, 1, 1, 1, "relu");
    Layer *l17 = make_convolutional_layer(512, 3, 1, 1, 1, "relu");
    Layer *l18 = make_maxpool_layer(2, 2, 0);
    Layer *l19 = make_connect_layer(4096, 1, "relu");
    Layer *l20 = make_dropout_layer(0.5);
    Layer *l21 = make_connect_layer(4096, 1, "relu");
    Layer *l22 = make_dropout_layer(0.5);
    Layer *l23 = make_connect_layer(2, 1, "linear");
    Layer *l24 = make_crossentropy_layer(2);
    append_layer2grpah(g, l1);
    append_layer2grpah(g, l2);
    append_layer2grpah(g, l3);
    append_layer2grpah(g, l4);
    append_layer2grpah(g, l5);
    append_layer2grpah(g, l6);
    append_layer2grpah(g, l7);
    append_layer2grpah(g, l8);
    append_layer2grpah(g, l9);
    append_layer2grpah(g, l10);
    append_layer2grpah(g, l11);
    append_layer2grpah(g, l12);
    append_layer2grpah(g, l13);
    append_layer2grpah(g, l14);
    append_layer2grpah(g, l15);
    append_layer2grpah(g, l16);
    append_layer2grpah(g, l17);
    append_layer2grpah(g, l18);
    append_layer2grpah(g, l19);
    append_layer2grpah(g, l20);
    append_layer2grpah(g, l21);
    append_layer2grpah(g, l22);
    append_layer2grpah(g, l23);
    append_layer2grpah(g, l24);
    Session *sess = create_session(g, 224, 224, 3, 2, type, path);
    float *mean = calloc(3, sizeof(float));
    float *std = calloc(3, sizeof(float));
    mean[0] = 0.485;
    mean[1] = 0.456;
    mean[2] = 0.406;
    std[0] = 0.229;
    std[1] = 0.224;
    std[2] = 0.225;
    transform_normalize_sess(sess, mean, std);
    transform_resize_sess(sess, 224, 224);
    set_detect_params(sess);
    init_session(sess, "./data/dogvscat/train.txt", "./data/dogvscat/train_label.txt");
    detect_classification(sess);
}
